### ISSUE TITLE
Laughing panda is down

### ISSUE THREAD

**Issue by hamza3202** [reaktor/log4j-email-throttle#2]
Hi, It seems like laughing panda is down ATM. I tried building the application locally but turns out, there are some dependencies that require laughingpanda. Any workarounds?

**Comment by sauri1** [comment]
Domain was expired due human error. Domain is now renewed and should work soon.

**Comment by sauri1** [comment]
maven.laughingpanda.org should resolve now.

**Comment by jkytomak** [comment]
Yes, it works again.
Thank you @sauri1 !
